# Generated by Django 4.1.2 on 2022-11-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DateRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_phase", models.CharField(default="", max_length=1000)),
                ("uid", models.CharField(default="", max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="PeriodData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diary_text", models.CharField(default="", max_length=1000)),
                ("blood_level", models.IntegerField(default=0)),
                ("pain_level", models.IntegerField(default=0)),
                ("uid", models.CharField(default="", max_length=1000)),
                ("date", models.TextField(default="", max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_year", models.IntegerField()),
                ("period_length", models.IntegerField()),
                ("cycle_length", models.IntegerField()),
                ("luteal_length", models.IntegerField()),
            ],
        ),
    ]
