# Generated by Django 4.1.1 on 2022-11-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_period", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=200)),
                ("uid", models.CharField(default="", max_length=1000)),
            ],
        ),
    ]
