# Generated by Django 4.1.1 on 2022-10-20 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_period", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Todo",),
    ]
