# Generated by Django 4.1.1 on 2022-10-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_period", "0002_delete_todo"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diary_text", models.CharField(max_length=400)),
                ("blood_level", models.DateTimeField(verbose_name="store blood level")),
                ("pain_level", models.DateTimeField(verbose_name="store pain level")),
            ],
        ),
    ]
