# Generated by Django 4.1.2 on 2022-11-15 07:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_period", "0004_setting"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diary_text", models.CharField(max_length=400)),
                ("blood_level", models.IntegerField()),
                ("pain_level", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PredictCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        default=datetime.datetime(2022, 11, 15, 14, 7, 18, 412684)
                    ),
                ),
                (
                    "setting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api_period.setting",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="HomePage",),
    ]
