# Generated by Django 4.1.2 on 2022-11-15 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_period", "0005_perioddata_predictcalendar_delete_homepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictcalendar",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 15, 14, 10, 26, 684029)
            ),
        ),
    ]
