# Generated by Django 4.1.2 on 2022-11-15 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_period", "0006_alter_predictcalendar_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perioddata",
            name="diary_text",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="predictcalendar",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 15, 21, 42, 40, 634179)
            ),
        ),
    ]
