# Generated by Django 4.1.2 on 2022-11-18 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_period", "0007_alter_perioddata_diary_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perioddata",
            name="blood_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="perioddata",
            name="diary_text",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="perioddata",
            name="pain_level",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="predictcalendar",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 18, 11, 34, 30, 723343)
            ),
        ),
    ]
