# Generated by Django 4.1.2 on 2022-11-18 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_period", "0009_perioddata_end_date_perioddata_start_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perioddata",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 18, 13, 2, 37, 695920)
            ),
        ),
        migrations.AddField(
            model_name="perioddata",
            name="uid",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="perioddata",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 18, 13, 2, 37, 695912)
            ),
        ),
        migrations.AlterField(
            model_name="perioddata",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 18, 13, 2, 37, 695903)
            ),
        ),
        migrations.AlterField(
            model_name="predictcalendar",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 18, 13, 2, 37, 696169)
            ),
        ),
    ]
