# Generated by Django 4.1.2 on 2022-11-18 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_period", "0010_perioddata_date_perioddata_uid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perioddata",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 18, 21, 49, 42, 259262)
            ),
        ),
        migrations.AlterField(
            model_name="perioddata",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 18, 21, 49, 42, 259254)
            ),
        ),
        migrations.AlterField(
            model_name="perioddata",
            name="start_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 18, 21, 49, 42, 259245)
            ),
        ),
        migrations.AlterField(
            model_name="predictcalendar",
            name="start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 18, 21, 49, 42, 259494)
            ),
        ),
    ]
